name: Hello World

on:
  push:
jobs:
  hello-job:
    runs-on: ubuntu-latest
    steps:
      - name: My first step in GitHub Action
        run: echo "Hello Action on ${{ github.event_name }}"

      - name: My first step in GitHub Action
        run: echo "Hello Action in ${{ github.repository }} ref - ${{ github.ref }}"

      - name: This GitHub Action is running on ${{ runner.os }}
        run: echo "Action job status ${{ job.status }}"